# Use the official Python image as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file from the bot-test directory and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable
ENV ADB_DEVICE_NAME="emulator-5554"

# Copy the test script into the container
COPY test_bot.py .

# Set the command to run the test script
CMD ["python", "-u", "test_bot.py"]
