# Use the official Appium Docker image
FROM appium/appium

# Update the UIAutomator2 driver if needed
RUN appium driver update uiautomator2

# Expose Appium server port
EXPOSE 4723

# Start the Appium server
CMD ["appium", "--address", "0.0.0.0", "--port", "4723"]
