version: '3.8'

services:
  telegram_bot:
    build:
      context: ../telegram-bot
      dockerfile: ../docker/Dockerfile.bot
    container_name: telegram-bot

  appium_server:
    build:
      context: ../test-bot
      dockerfile: ../docker/Dockerfile.appium
    container_name: appium-server
    network_mode: "host"  # Allows Appium to access ADB on the host
    environment:
      - APPIUM_LOG_LEVEL=info
      - RELAXED_SECURITY=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4723/status" ]  # Appium status check
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  bot_test:
    build:
      context: ../test-bot
      dockerfile: ../docker/Dockerfile.test
    container_name: bot-test
    network_mode: "host"
    environment:
      - ADB_DEVICE_NAME=${ADB_DEVICE_NAME}
    depends_on:
      appium_server:
        condition: service_healthy
